// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxqszgiZx1MxWQ3XHRp-ZXroZpIAdxAK8',
    appId: '1:310693586010:web:7c5f06421361ffe2872463',
    messagingSenderId: '310693586010',
    projectId: 'hidrotech-3f389',
    authDomain: 'hidrotech-3f389.firebaseapp.com',
    storageBucket: 'hidrotech-3f389.appspot.com',
    measurementId: 'G-6YFVVFQH1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFWrHb8sjXTlraqzdESvzpYrgpHOJoJ0k',
    appId: '1:310693586010:android:1f6d75ef630494e7872463',
    messagingSenderId: '310693586010',
    projectId: 'hidrotech-3f389',
    storageBucket: 'hidrotech-3f389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQdSqwWRbuAwzKCuEGE2zavbjkVCc1Xyc',
    appId: '1:310693586010:ios:50167c0521994acc872463',
    messagingSenderId: '310693586010',
    projectId: 'hidrotech-3f389',
    storageBucket: 'hidrotech-3f389.appspot.com',
    iosBundleId: 'com.example.hidroTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQdSqwWRbuAwzKCuEGE2zavbjkVCc1Xyc',
    appId: '1:310693586010:ios:50167c0521994acc872463',
    messagingSenderId: '310693586010',
    projectId: 'hidrotech-3f389',
    storageBucket: 'hidrotech-3f389.appspot.com',
    iosBundleId: 'com.example.hidroTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxqszgiZx1MxWQ3XHRp-ZXroZpIAdxAK8',
    appId: '1:310693586010:web:7c45d124082561ce872463',
    messagingSenderId: '310693586010',
    projectId: 'hidrotech-3f389',
    authDomain: 'hidrotech-3f389.firebaseapp.com',
    storageBucket: 'hidrotech-3f389.appspot.com',
    measurementId: 'G-DY9ZSQ03Y6',
  );

}